import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_EG': {
          'Language': 'اللغة',
          'Sales': 'مبيعات',
          'Purchases': 'مشتريات',
          'Vendors': 'موردين',
          'Clients': 'عملاء',
          'Expenses': 'مصروفات',
          'Cash': 'صندوق',
          'Reports': 'تقارير',
          'Inventory': 'مخزون',
          'POS': 'نقطة',
          'Search by id or name': 'ابحث بالرقم التعريفي أو الاسم',
          'Pay': 'حاسب',
          'Barcode Scanner': 'قارئ الباركود',
          'Camera Inaccessible': 'لا يمكن الوصول للكاميرا',
          'We cannot access camera now, please try again':
              'لم نتمكن من الوصول للكاميرا، حاول مجددًا',
          'failed to read': 'فشل القراءة',
          'General settings': 'إعدادات عامة',
          'Edit products': 'تعديل المنتجات',
          'Products': 'المنتجات',
          'categories': 'التصنيفات',
          'New Category': 'إضافة تصنيف',
          'Display categories': 'عرض التصنيفات',
          'Edit category': 'تعديل تصنيف',
          'Price lists': 'قوائم الأسعار',
          'Display price lists': 'عرض قوائم الأسعار',
          'Edit price list': 'تعديل قائمة أسعار',
          'New product': 'منتج جديد',
          'Display products': 'عرض المنتجات',
          'New price list': 'إضافة قائمة أسعار',
          'Import products from Excel file': 'استيراد منتجات من ملف اكسل',
          'Category name': 'اسم التصنيف',
          'Save': 'حفظ',
          'Please enter value': 'يجب إدخال قيمة',
          'categories are empty': 'التصنيفات فارغة',
          'Category name already exists': 'اسم التصنيف مكرر',
          'Repetitive Name': 'الإسم مكرر',
          'Price lists are empty': 'قوائم الأسعار فارغة',
          'Price list name': 'اسم قائمة الأسعار',
          'Price list name already exists': 'اسم قائمة الأسعار مكرر',
          'Please define price lists names in Store management':
              'فضلًا قم بتعريف قوائم الأسعار في إدارة المخزون أولًا',
          'New Product': 'منتج جديد',
          'Taxes': 'الضرائب',
          'No taxes defined': 'لا توجد ضرائب معرفة',
          'New tax': 'ضريبة جديدة',
          'Price tax name': 'من فضلك أدخل اسم الضريبة',
          'Tax name already exists': 'اسم الضريبة مكرر',
          'Edit Tax': 'تعديل الضريبة',
          'Inventory Management': 'إدارة المخزون',
          'Product details': 'تفاصيل المنتج',
          'Product taxes': 'ضرائب المنتج',
          'Product units': 'وحدات المنتج',
          'Product prices': 'أسعار المنتج',
          'Please define taxes in Store management':
              'فضلًا قم بتعريف الضرائب في إدارة المخزون أولًا',
          'Tax Name': 'اسم الضريبة',
          'Tax Percentage %': 'نسبة الضريبة ٪',
          'Tax updated': 'تحديث الضريبة',
          'product name': 'اسم المنتج',
          'product description': 'وصف المنتج',
          'product prices': 'أسعار المنتج',
          'quantity': 'الكمية',
          'average opening price': 'متوسط سعر افتتاحي',
          'notify when quantity reach': 'نبهني عند وصول الكمية إلى',
          'Price List Name': 'اسم قائمة الأسعار',
          'Value': 'القيمة',
          'Opening Inventory': 'الرصيد الافتتاحي',
          'category': 'تصنيف',
          'General': 'عام',
          'choose a category': 'اختر تصنيف',
          'Categories': 'التصنيفات',
        },
      };
}
